version: '3.3'
services:
        rabbitmq:
                image: rabbitmq:management
                environment:
                        RABBITMQ_DEFAULT_USER: celery
                        RABBITMQ_DEFAULT_PASS: pw123456
                        RABBITMQ_DEFAULT_VHOST: celery_vhost
                ports:
                        - "5672:5672"
                        - "15672:15672"
                expose:
                        - 15672
        celery:
                build: ./celery
                command: sh run.sh
                restart: always
                depends_on:
                        - rabbitmq
        app:
                build: ./django
                command: sh build.sh
                restart: always
                ports:
                        - "80:8000"
                volumes:
                        - api_data:/docker_api
                depends_on:
                        - rabbitmq
volumes:
        api_data:

