version: '3.3'
services:
        app:
                build: .
                command: sh build.sh
                restart: always
                ports:
                        - "80:8000"
                volumes:
                        - .:/nicetomeetyou

