version: '3.3'
services:
        app:
                build: .
                command: python manage.py runserver 0.0.0.0:8000
                restart: always
                ports:
                        - "80:8000"
                volumes:
                        - .:/nicetomeetyou

